apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.tenantNamespace }}
  labels:
    app: auth-service
    version: v1
spec:
  ports:
  - name: grpc
    targetPort: {{ .Values.service.port }}
    port: {{ .Values.service.port }}
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpPort }} 
  selector:
    app: auth-service